[project]
name = "csv_validator"
version = "0.0.0"
description = "A CSV validator for Guardrails AI."
authors = [
    {name = "Hyperparam", email = "kenny@hyperparam.app"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">= 3.8.1"
dependencies = [
    "guardrails-ai>=0.4.0",
]